# /deploy/frontend/nginx.conf
server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* ^/\w+\.json-seq(.gz)?$ {
        alias /usr/share/nginx/html/data/;
        add_header Content-Type "application/json-seq; charset=utf-8";
        gzip_static on;
    }

    # Optional: Add security headers, gzip compression, etc.
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    types { application/json-seq json-seq; }
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
}
