# /posh nginx.conf
gzip on;
gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_types 
    text/plain 
    text/css 
    application/json 
    application/javascript 
    application/x-javascript 
    text/xml 
    application/xml 
    application/xml+rss 
    text/javascript 
    application/json-seq;

server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* ^/\w+\.json-seq(.gz)?$ {
        root /usr/share/nginx/html/data/sequence/latest;
        default_type application/json-seq;
        gzip_static always;
        gunzip on;
    }

    # Optional: Add security headers, gzip compression, etc.
    
}
